
package Vista;


import Controlador.C_Articulo3597;
import Controlador.C_Conexion3597;
import Modelo.Articulo_3597;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class F_Articulo_3597 extends javax.swing.JFrame {

    C_Articulo3597 c_articulo3597 = new C_Articulo3597();
    C_Conexion3597 c_conexion3597 = new C_Conexion3597();
    
            
    /** Creates new form F_Articulo_3597 */
    public F_Articulo_3597(){
        initComponents();
        
        txNombre.requestFocus();
        lbCod.setText(c_articulo3597.CodigoContador());
        
        TableData();
        
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        sNombre = new javax.swing.JSeparator();
        lbDescripcion = new javax.swing.JLabel();
        txDescripcion = new javax.swing.JTextField();
        sDescripcion = new javax.swing.JSeparator();
        lbCantidad = new javax.swing.JLabel();
        txCantidad = new javax.swing.JTextField();
        sCantidad = new javax.swing.JSeparator();
        lbTelefono = new javax.swing.JLabel();
        txPrecioU = new javax.swing.JTextField();
        sPrecioU = new javax.swing.JSeparator();
        bttReporte = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttAgregar1 = new javax.swing.JButton();
        bttModificar1 = new javax.swing.JButton();
        bttEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaArticulo = new javax.swing.JTable();
        bttLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_Articulo = new javax.swing.JTextArea();
        lbCodigoP = new javax.swing.JLabel();
        txCodigoP = new javax.swing.JTextField();
        sCodigoP = new javax.swing.JSeparator();
        lbCod = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(700, 700));
        background.setPreferredSize(new java.awt.Dimension(700, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("ARTÍCULO");
        background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, 40));

        lbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(51, 0, 51));
        lbCodigo.setText("Código: ");
        background.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lbNombre.setBackground(new java.awt.Color(255, 255, 255));
        lbNombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(51, 0, 51));
        lbNombre.setText("Nombre:");
        background.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txNombre.setBackground(new java.awt.Color(255, 255, 255));
        txNombre.setForeground(new java.awt.Color(0, 0, 0));
        txNombre.setBorder(null);
        txNombre.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 183, -1));
        background.add(sNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 161, 15));

        lbDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lbDescripcion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(51, 0, 51));
        lbDescripcion.setText("Descripción:");
        background.add(lbDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txDescripcion.setBorder(null);
        txDescripcion.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, 40));
        background.add(sDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, 15));

        lbCantidad.setBackground(new java.awt.Color(255, 255, 255));
        lbCantidad.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(51, 0, 51));
        lbCantidad.setText("Cantidad:");
        background.add(lbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txCantidad.setBorder(null);
        txCantidad.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 183, -1));
        background.add(sCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 161, 15));

        lbTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lbTelefono.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(51, 0, 51));
        lbTelefono.setText("Precio Unitario:");
        background.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txPrecioU.setBackground(new java.awt.Color(255, 255, 255));
        txPrecioU.setForeground(new java.awt.Color(0, 0, 0));
        txPrecioU.setBorder(null);
        txPrecioU.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 340, 140, -1));
        background.add(sPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 360, 120, 20));

        bttReporte.setBackground(new java.awt.Color(102, 0, 102));
        bttReporte.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttReporte.setForeground(new java.awt.Color(204, 204, 204));
        bttReporte.setText("Reporte");
        bttReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });
        background.add(bttReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 110, 30));

        bttBuscar.setBackground(new java.awt.Color(102, 0, 102));
        bttBuscar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        background.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 110, 30));

        bttAgregar1.setBackground(new java.awt.Color(102, 0, 102));
        bttAgregar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttAgregar1.setForeground(new java.awt.Color(204, 204, 204));
        bttAgregar1.setText("Agregar");
        bttAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregar1ActionPerformed(evt);
            }
        });
        background.add(bttAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 30));

        bttModificar1.setBackground(new java.awt.Color(102, 0, 102));
        bttModificar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar1.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar1.setText("Modificar");
        bttModificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar1ActionPerformed(evt);
            }
        });
        background.add(bttModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 110, 30));

        bttEliminar1.setBackground(new java.awt.Color(102, 0, 102));
        bttEliminar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        bttEliminar1.setText("Eliminar");
        bttEliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminar1ActionPerformed(evt);
            }
        });
        background.add(bttEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 110, 30));

        TablaArticulo.setBackground(new java.awt.Color(255, 255, 255));
        TablaArticulo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        TablaArticulo.setForeground(new java.awt.Color(51, 0, 51));
        TablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombre", "Descripción", "Cantidad", "Precio Unitario", "Cod. Prov."
            }
        ));
        TablaArticulo.setGridColor(new java.awt.Color(0, 0, 0));
        TablaArticulo.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TablaArticulo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaArticulo);
        if (TablaArticulo.getColumnModel().getColumnCount() > 0) {
            TablaArticulo.getColumnModel().getColumn(0).setMinWidth(30);
            TablaArticulo.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaArticulo.getColumnModel().getColumn(0).setMaxWidth(30);
            TablaArticulo.getColumnModel().getColumn(5).setMinWidth(50);
            TablaArticulo.getColumnModel().getColumn(5).setPreferredWidth(50);
            TablaArticulo.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 520, 320));

        bttLimpiar.setBackground(new java.awt.Color(102, 0, 102));
        bttLimpiar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("Limpiar");
        bttLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        background.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 110, 30));

        jta_Articulo.setBackground(new java.awt.Color(235, 235, 235));
        jta_Articulo.setColumns(20);
        jta_Articulo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jta_Articulo.setForeground(new java.awt.Color(0, 0, 0));
        jta_Articulo.setRows(5);
        jta_Articulo.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jta_Articulo.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane3.setViewportView(jta_Articulo);

        background.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 580, 50));

        lbCodigoP.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigoP.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigoP.setForeground(new java.awt.Color(51, 0, 51));
        lbCodigoP.setText("Código de Proveedor:");
        background.add(lbCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txCodigoP.setBackground(new java.awt.Color(255, 255, 255));
        txCodigoP.setForeground(new java.awt.Color(0, 0, 0));
        txCodigoP.setBorder(null);
        txCodigoP.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 400, 100, -1));
        background.add(sCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, 15));

        lbCod.setBackground(new java.awt.Color(255, 255, 255));
        lbCod.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCod.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 50, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        c_articulo3597.AbrirURL(c_articulo3597.Reporte());
    }//GEN-LAST:event_bttReporteActionPerformed

    private void bttAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregar1ActionPerformed
        
        if (txNombre.getText().isEmpty() || 
            txDescripcion.getText().isEmpty() || txCantidad.getText().isEmpty() ||
            txPrecioU.getText().isEmpty() || txCodigoP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese todos los campos");
        }
        else
        {
            Articulo_3597 a = new Articulo_3597();
            a.setNombre(txNombre.getText());
            a.setDescripción(txDescripcion.getText());
            a.setCantidad(parseInt(txCantidad.getText()));
            a.setPrecioUnitario(parseDouble(txPrecioU.getText()));
            a.setcProveedor(parseInt(txCodigoP.getText()));
            
            c_articulo3597.AgregarArticulo(a);
            lbCod.setText(c_articulo3597.CodigoContador());
            LimpiarTabla();
            limpiar();
        }
    }//GEN-LAST:event_bttAgregar1ActionPerformed

    private void bttModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar1ActionPerformed
        if (txNombre.getText().isEmpty() || 
            txDescripcion.getText().isEmpty() || txCantidad.getText().isEmpty() ||
            txPrecioU.getText().isEmpty() || txCodigoP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, Ingrese todos los campos");
        }
        else{
            Articulo_3597 a = new Articulo_3597(parseInt(lbCod.getText()),
                                                  txNombre.getText(),
                                                  txDescripcion.getText(),
                                                  parseInt(txCantidad.getText()),
                                                  parseDouble(txPrecioU.getText()),
                                                  parseInt(txCodigoP.getText()));
            
           c_articulo3597.ModificarArticulo(a);
           lbCod.setText(c_articulo3597.CodigoContador());
           LimpiarTabla();
           limpiar();
        }
    }//GEN-LAST:event_bttModificar1ActionPerformed

    private void bttEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminar1ActionPerformed
        String cod = JOptionPane.showInputDialog("Ingrese código de Articulo a ELIMINAR");
            
        c_articulo3597.EliminarArticulo(cod);
        LimpiarTabla();
        limpiar();
    }//GEN-LAST:event_bttEliminar1ActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed
        String cod = JOptionPane.showInputDialog("Ingrese código de Articulo a buscar: ");

        String sql = "";
        sql = "select * from Articulos where Articulos.codigo = "+ cod + ";";

        try {
            Statement comando = c_conexion3597.establecerConexion().createStatement();
            ResultSet registro = comando.executeQuery(sql);
            
            if (registro.next()) {
                lbCod.setText(registro.getString("codigo"));
                txNombre.setText(registro.getString("nombre"));
                txDescripcion.setText(registro.getString("descripcion"));
                txCantidad.setText(registro.getString("cantidad"));
                txPrecioU.setText(registro.getString("precio"));
                txCodigoP.setText(registro.getString("fkproveedor"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Código no existente");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar esta acción: " + e);
        } finally {
            c_conexion3597.closeConexion();
        }
    }//GEN-LAST:event_bttBuscarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void limpiar(){  
        lbCod.setText(c_articulo3597.CodigoContador());
        jta_Articulo.setText("");
        txNombre.setText("");
        txDescripcion.setText("");
        txCantidad.setText("");
        txPrecioU.setText("");
        txCodigoP.setText("");
        
        txNombre.requestFocus();
    }
  
    private void LimpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
        modelo.getDataVector().removeAllElements();
        TablaArticulo.updateUI();
        
        TableData();
    }    
    
    private void TableData(){
        String sql = "";
        sql = "select * from Articulos;";
            
        try {
            Statement comando = c_conexion3597.establecerConexion().createStatement();
            ResultSet registro = comando.executeQuery(sql);

            while (registro.next()){

                DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
                Object[] fila = new Object[6];
                fila[0] = registro.getString("codigo");
                fila[1] = registro.getString("nombre");
                fila[2] = registro.getString("descripcion");
                fila[3] = registro.getString("cantidad");
                fila[4] = registro.getString("precio");
                fila[5] = registro.getString("fkproveedor");
                modelo.addRow(fila); 
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            c_conexion3597.closeConexion();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Articulo_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Articulo_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Articulo_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Articulo_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Articulo_3597().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaArticulo;
    private javax.swing.JPanel background;
    private javax.swing.JButton bttAgregar1;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttEliminar1;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar1;
    private javax.swing.JButton bttReporte;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jta_Articulo;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoP;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JSeparator sCantidad;
    private javax.swing.JSeparator sCodigoP;
    private javax.swing.JSeparator sDescripcion;
    private javax.swing.JSeparator sNombre;
    private javax.swing.JSeparator sPrecioU;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txCodigoP;
    private javax.swing.JTextField txDescripcion;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txPrecioU;
    // End of variables declaration//GEN-END:variables

}
