
package Vista;

import Controlador.AB_Cliente3597;
import Controlador.C_Cliente3597;
import Controlador.C_Conexion3597;
import Modelo.Cliente_3597;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class F_Cliente_3597 extends javax.swing.JFrame {

    C_Cliente3597 c_cliente3597 = new C_Cliente3597();
    C_Conexion3597 c_conexion3597 = new C_Conexion3597();
            
    public F_Cliente_3597(){
        initComponents();

        lbCODIGO.setText(c_cliente3597.CodigoContador());
        TableData();
        txNIT.requestFocus();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);    
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbNIT = new javax.swing.JLabel();
        txNIT = new javax.swing.JTextField();
        sNIT = new javax.swing.JSeparator();
        lbNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        sNombre = new javax.swing.JSeparator();
        lbApellido = new javax.swing.JLabel();
        txApellido = new javax.swing.JTextField();
        sApellido = new javax.swing.JSeparator();
        lbDPI = new javax.swing.JLabel();
        txDPI = new javax.swing.JTextField();
        sDPI = new javax.swing.JSeparator();
        lbDireccion = new javax.swing.JLabel();
        txDirección = new javax.swing.JTextField();
        sDireccion = new javax.swing.JSeparator();
        bttReporte = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttAgregar1 = new javax.swing.JButton();
        bttModificar1 = new javax.swing.JButton();
        bttEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        bttLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_Cliente = new javax.swing.JTextArea();
        lbEdad = new javax.swing.JLabel();
        txEdad = new javax.swing.JTextField();
        sEdad = new javax.swing.JSeparator();
        lbTelefono = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        sTelefono = new javax.swing.JSeparator();
        lbCodigo = new javax.swing.JLabel();
        lbCODIGO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(700, 700));
        background.setPreferredSize(new java.awt.Dimension(700, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("CLIENTE");
        background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 150, 40));

        lbNIT.setBackground(new java.awt.Color(255, 255, 255));
        lbNIT.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNIT.setForeground(new java.awt.Color(51, 0, 51));
        lbNIT.setText("NIT:");
        background.add(lbNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txNIT.setBackground(new java.awt.Color(255, 255, 255));
        txNIT.setForeground(new java.awt.Color(0, 0, 0));
        txNIT.setBorder(null);
        txNIT.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, -1));
        background.add(sNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, 15));

        lbNombre.setBackground(new java.awt.Color(255, 255, 255));
        lbNombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(51, 0, 51));
        lbNombre.setText("Nombre:");
        background.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txNombre.setBackground(new java.awt.Color(255, 255, 255));
        txNombre.setForeground(new java.awt.Color(0, 0, 0));
        txNombre.setBorder(null);
        txNombre.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, -1));
        background.add(sNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 161, 15));

        lbApellido.setBackground(new java.awt.Color(255, 255, 255));
        lbApellido.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(51, 0, 51));
        lbApellido.setText("Apellido:");
        background.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txApellido.setBackground(new java.awt.Color(255, 255, 255));
        txApellido.setForeground(new java.awt.Color(0, 0, 0));
        txApellido.setBorder(null);
        txApellido.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, 20));
        background.add(sApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, 15));

        lbDPI.setBackground(new java.awt.Color(255, 255, 255));
        lbDPI.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDPI.setForeground(new java.awt.Color(51, 0, 51));
        lbDPI.setText("DPI:");
        background.add(lbDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txDPI.setBackground(new java.awt.Color(255, 255, 255));
        txDPI.setForeground(new java.awt.Color(0, 0, 0));
        txDPI.setBorder(null);
        txDPI.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 160, -1));
        background.add(sDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 161, 15));

        lbDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lbDireccion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(51, 0, 51));
        lbDireccion.setText("Dirección:");
        background.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txDirección.setBackground(new java.awt.Color(255, 255, 255));
        txDirección.setForeground(new java.awt.Color(0, 0, 0));
        txDirección.setBorder(null);
        txDirección.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, -1));
        background.add(sDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 160, 20));

        bttReporte.setBackground(new java.awt.Color(102, 0, 102));
        bttReporte.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttReporte.setForeground(new java.awt.Color(204, 204, 204));
        bttReporte.setText("Reporte");
        bttReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });
        background.add(bttReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 110, 30));

        bttBuscar.setBackground(new java.awt.Color(102, 0, 102));
        bttBuscar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        background.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 110, 30));

        bttAgregar1.setBackground(new java.awt.Color(102, 0, 102));
        bttAgregar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttAgregar1.setForeground(new java.awt.Color(204, 204, 204));
        bttAgregar1.setText("Agregar");
        bttAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregar1ActionPerformed(evt);
            }
        });
        background.add(bttAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 110, 30));

        bttModificar1.setBackground(new java.awt.Color(102, 0, 102));
        bttModificar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar1.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar1.setText("Modificar");
        bttModificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar1ActionPerformed(evt);
            }
        });
        background.add(bttModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 110, 30));

        bttEliminar1.setBackground(new java.awt.Color(102, 0, 102));
        bttEliminar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        bttEliminar1.setText("Eliminar");
        bttEliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminar1ActionPerformed(evt);
            }
        });
        background.add(bttEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 110, 30));

        TablaCliente.setBackground(new java.awt.Color(255, 255, 255));
        TablaCliente.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        TablaCliente.setForeground(new java.awt.Color(51, 0, 51));
        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "NIT", "Nombre", "Apellido", "DPI", "Dirección", "Edad", "Teléfono"
            }
        ));
        TablaCliente.setGridColor(new java.awt.Color(0, 0, 0));
        TablaCliente.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TablaCliente.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaCliente);
        if (TablaCliente.getColumnModel().getColumnCount() > 0) {
            TablaCliente.getColumnModel().getColumn(0).setMinWidth(30);
            TablaCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaCliente.getColumnModel().getColumn(0).setMaxWidth(30);
            TablaCliente.getColumnModel().getColumn(6).setMinWidth(40);
            TablaCliente.getColumnModel().getColumn(6).setPreferredWidth(40);
            TablaCliente.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 580, 370));

        bttLimpiar.setBackground(new java.awt.Color(102, 0, 102));
        bttLimpiar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("Limpiar");
        bttLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        background.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 110, 30));

        jta_Cliente.setBackground(new java.awt.Color(235, 235, 235));
        jta_Cliente.setColumns(20);
        jta_Cliente.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jta_Cliente.setForeground(new java.awt.Color(0, 0, 0));
        jta_Cliente.setRows(5);
        jta_Cliente.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jta_Cliente.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane3.setViewportView(jta_Cliente);

        background.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 650, 50));

        lbEdad.setBackground(new java.awt.Color(255, 255, 255));
        lbEdad.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbEdad.setForeground(new java.awt.Color(51, 0, 51));
        lbEdad.setText("Edad:");
        background.add(lbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txEdad.setBackground(new java.awt.Color(255, 255, 255));
        txEdad.setForeground(new java.awt.Color(0, 0, 0));
        txEdad.setBorder(null);
        txEdad.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 160, -1));
        background.add(sEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 160, 15));

        lbTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lbTelefono.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(51, 0, 51));
        lbTelefono.setText("Teléfono:");
        background.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        txTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txTelefono.setBorder(null);
        txTelefono.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 160, -1));
        background.add(sTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 160, 15));

        lbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(51, 0, 51));
        lbCodigo.setText("Código No.");
        background.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lbCODIGO.setBackground(new java.awt.Color(102, 102, 102));
        lbCODIGO.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCODIGO.setForeground(new java.awt.Color(51, 0, 51));
        lbCODIGO.setToolTipText("");
        background.add(lbCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 20));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        c_cliente3597.AbrirURL(c_cliente3597.Reporte());
    }//GEN-LAST:event_bttReporteActionPerformed

    private void bttAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregar1ActionPerformed
        
        if (txNIT.getText().isEmpty() || txNombre.getText().isEmpty() || 
            txApellido.getText().isEmpty() || txDPI.getText().isEmpty() ||
            txDirección.getText().isEmpty() || txEdad.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese todos los campos");
        }
        else
        {
            Cliente_3597 c = new Cliente_3597();
            c.setNIT(txNIT.getText());    
            c.setNombre(txNombre.getText());
            c.setApellido(txApellido.getText());
            c.setDPI(txDPI.getText());
            c.setDireccion(txDirección.getText());
            c.setEdad(txEdad.getText());
            c.setTelefono(txTelefono.getText());
            
            c_cliente3597.AgregarCliente(c);
            lbCODIGO.setText(c_cliente3597.CodigoContador());
            LimpiarTabla();
            limpiar();
            
        }
    }//GEN-LAST:event_bttAgregar1ActionPerformed

    private void bttModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar1ActionPerformed
        if (txNIT.getText().isEmpty() || txNombre.getText().isEmpty() || 
            txApellido.getText().isEmpty() || txDPI.getText().isEmpty() ||
            txDirección.getText().isEmpty() || txEdad.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, Ingrese todos los campos");
        }
        else{
            Cliente_3597 c = new Cliente_3597();
            c.setCodigo(Integer.parseInt(lbCODIGO.getText()));
            c.setNIT(txNIT.getText());    
            c.setNombre(txNombre.getText());
            c.setApellido(txApellido.getText());
            c.setDPI(txDPI.getText());
            c.setDireccion(txDirección.getText());
            c.setEdad(txEdad.getText());
            c.setTelefono(txTelefono.getText());
            
            c_cliente3597.ModificarCliente(c);
            lbCODIGO.setText(c_cliente3597.CodigoContador());
            
            LimpiarTabla();
            limpiar();
        }
    }//GEN-LAST:event_bttModificar1ActionPerformed

    private void bttEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminar1ActionPerformed
        String cod = JOptionPane.showInputDialog("Ingrese código de Cliente a ELIMINAR");
        
        c_cliente3597.EliminarCliente(cod);
        
        LimpiarTabla();
        limpiar();
    }//GEN-LAST:event_bttEliminar1ActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed

        String cod = JOptionPane.showInputDialog("Ingrese código de cliente a buscar: ");
        String sql = "select * from Clientes where codigo =" + cod + ";";
        
        try {
            Statement consulta = c_conexion3597.establecerConexion().createStatement();
            ResultSet registro = consulta.executeQuery(sql);
            
            if (registro.next()){
                lbCODIGO.setText(registro.getString("codigo"));
                txNIT.setText(registro.getString("NIT"));
                txNombre.setText(registro.getString("nombre"));
                txApellido.setText(registro.getString("apellido"));
                txDPI.setText(registro.getString("DPI"));
                txDirección.setText(registro.getString("direccion"));
                txEdad.setText(registro.getString("edad"));
                txTelefono.setText(registro.getString("telefono"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Código de Cliente no existente");
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar esta acción: " + e);
        } finally {
            c_conexion3597.closeConexion();
        }
    }//GEN-LAST:event_bttBuscarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void limpiar(){  
        lbCODIGO.setText(c_cliente3597.CodigoContador());
        
        jta_Cliente.setText("");
        txNIT.setText("");
        txNombre.setText("");
        txApellido.setText("");
        txDPI.setText("");
        txDirección.setText("");
        txEdad.setText("");
        txTelefono.setText("");
                        
        txNIT.requestFocus();
    }
    
    private void LimpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) TablaCliente.getModel();
        modelo.getDataVector().removeAllElements();
        TablaCliente.updateUI();
        
        TableData();
    }
    
    private void TableData(){
        
        String sql = "select * from Clientes;";
        
        try {
            Statement comando = c_conexion3597.establecerConexion().createStatement();
            ResultSet registro = comando.executeQuery(sql);
            
            while (registro.next()){
                DefaultTableModel modelo = (DefaultTableModel) TablaCliente.getModel();
                Object[] fila = new Object[8];
                fila[0] = registro.getString("codigo");
                fila[1] = registro.getString("NIT");
                fila[2] = registro.getString("nombre");
                fila[3] = registro.getString("apellido");
                fila[4] = registro.getString("DPI");
                fila[5] = registro.getString("direccion");
                fila[6] = registro.getString("edad");
                fila[7] = registro.getString("telefono");
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            c_conexion3597.closeConexion();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Cliente_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Cliente_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Cliente_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Cliente_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Cliente_3597().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCliente;
    private javax.swing.JPanel background;
    private javax.swing.JButton bttAgregar1;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttEliminar1;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar1;
    private javax.swing.JButton bttReporte;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jta_Cliente;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCODIGO;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDPI;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbNIT;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JSeparator sApellido;
    private javax.swing.JSeparator sDPI;
    private javax.swing.JSeparator sDireccion;
    private javax.swing.JSeparator sEdad;
    private javax.swing.JSeparator sNIT;
    private javax.swing.JSeparator sNombre;
    private javax.swing.JSeparator sTelefono;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txDPI;
    private javax.swing.JTextField txDirección;
    private javax.swing.JTextField txEdad;
    private javax.swing.JTextField txNIT;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables

}
