/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.*;
import Modelo.*;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class F_Factura extends javax.swing.JFrame {

    private ArrayList<Articulo_3597> A, art = new ArrayList();
    private ArrayList<Empleado> E = new ArrayList();
    private ArrayList<Cliente_3597> C = new ArrayList();
    private ArrayList<DetalleFactura_3597> D = new ArrayList();
    
    AB_Artículo3597 ab_Articulo3597;
    AB_Empleado ab_Empleado;
    AB_Cliente3597 ab_Cliente3597;
    AB_Factura3597 ab_Factura3597;
    
    public F_Factura() {
        initComponents();
                
        txNumero_Caja.requestFocus();
        
        ab_Articulo3597 = new AB_Artículo3597();
        ab_Empleado = new AB_Empleado();
        ab_Cliente3597 = new AB_Cliente3597();
        ab_Factura3597 = new AB_Factura3597();

        try {
            ab_Articulo3597.SalvarA_Articulo();
            ab_Empleado.SalvarA_Empleado();
            ab_Cliente3597.SalvarA_Cliente();
            ab_Factura3597.SalvarA_Factura();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(F_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYY");
        lbFecha.setText(formatoFecha.format(fecha));
        
        lbCorrelativo.setText(Integer.toString(ab_Factura3597.corelativoF()));        
        
//        TableData();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbCORRELATIVO = new javax.swing.JLabel();
        txCodArticulo = new javax.swing.JTextField();
        sID = new javax.swing.JSeparator();
        lbCArticulo = new javax.swing.JLabel();
        lbNombreARTICULO = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        txCantidad = new javax.swing.JTextField();
        sCantidad = new javax.swing.JSeparator();
        lbPRECIOunitario = new javax.swing.JLabel();
        bttReporte = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttGenerar = new javax.swing.JButton();
        bttModificar1 = new javax.swing.JButton();
        bttCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaArticulo = new javax.swing.JTable();
        bttLimpiar = new javax.swing.JButton();
        lbFECHA = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbCorrelativo = new javax.swing.JLabel();
        lbNombreArticulo = new javax.swing.JLabel();
        lbPrecioUnitario = new javax.swing.JLabel();
        bttAgregar_Articulo = new javax.swing.JButton();
        bttModificar_Articulo = new javax.swing.JButton();
        bttEliminar_Articulo = new javax.swing.JButton();
        bttBuscar_Artiulo = new javax.swing.JButton();
        lbCCliente = new javax.swing.JLabel();
        txNITcliente = new javax.swing.JTextField();
        sCodigoA = new javax.swing.JSeparator();
        lbNOMBREcliente = new javax.swing.JLabel();
        lbNombreCliente = new javax.swing.JLabel();
        lbNiT = new javax.swing.JLabel();
        lbCodigoCliente = new javax.swing.JLabel();
        btt_Buscar_Cliente = new javax.swing.JButton();
        lbIDcajero = new javax.swing.JLabel();
        txIDcajero = new javax.swing.JTextField();
        sCodigoC = new javax.swing.JSeparator();
        lbNUMEROcaja = new javax.swing.JLabel();
        txNumero_Caja = new javax.swing.JTextField();
        sCodigoE1 = new javax.swing.JSeparator();
        lbNOMBREempleado = new javax.swing.JLabel();
        lbNombreEmpleado = new javax.swing.JLabel();
        lbCEmpleado = new javax.swing.JLabel();
        lbCodEmpleado = new javax.swing.JLabel();
        btt_BuscarEmpleado = new javax.swing.JButton();
        bttVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(700, 700));
        background.setPreferredSize(new java.awt.Dimension(700, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("FACTURA");
        background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, 40));

        lbCORRELATIVO.setBackground(new java.awt.Color(255, 255, 255));
        lbCORRELATIVO.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCORRELATIVO.setForeground(new java.awt.Color(51, 0, 51));
        lbCORRELATIVO.setText("Correlativo: ");
        background.add(lbCORRELATIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txCodArticulo.setBackground(new java.awt.Color(255, 255, 255));
        txCodArticulo.setForeground(new java.awt.Color(0, 0, 0));
        txCodArticulo.setBorder(null);
        txCodArticulo.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCodArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 50, -1));
        background.add(sID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 50, 15));

        lbCArticulo.setBackground(new java.awt.Color(255, 255, 255));
        lbCArticulo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCArticulo.setForeground(new java.awt.Color(51, 0, 51));
        lbCArticulo.setText("Código de Artículo:");
        background.add(lbCArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        lbNombreARTICULO.setBackground(new java.awt.Color(255, 255, 255));
        lbNombreARTICULO.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombreARTICULO.setForeground(new java.awt.Color(51, 0, 51));
        lbNombreARTICULO.setText("Nombre:");
        background.add(lbNombreARTICULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        lbCantidad.setBackground(new java.awt.Color(255, 255, 255));
        lbCantidad.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(51, 0, 51));
        lbCantidad.setText("Cantidad:");
        background.add(lbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txCantidad.setForeground(new java.awt.Color(0, 0, 0));
        txCantidad.setBorder(null);
        txCantidad.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 120, -1));
        background.add(sCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 120, 15));

        lbPRECIOunitario.setBackground(new java.awt.Color(255, 255, 255));
        lbPRECIOunitario.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbPRECIOunitario.setForeground(new java.awt.Color(51, 0, 51));
        lbPRECIOunitario.setText("Precio Unitario:");
        background.add(lbPRECIOunitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        bttReporte.setBackground(new java.awt.Color(102, 0, 102));
        bttReporte.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttReporte.setForeground(new java.awt.Color(204, 204, 204));
        bttReporte.setText("Reporte");
        bttReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });
        background.add(bttReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 130, 30));

        bttBuscar.setBackground(new java.awt.Color(102, 0, 102));
        bttBuscar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        background.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 120, 30));

        bttGenerar.setBackground(new java.awt.Color(102, 0, 102));
        bttGenerar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttGenerar.setForeground(new java.awt.Color(204, 204, 204));
        bttGenerar.setText("Generar factura");
        bttGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGenerarActionPerformed(evt);
            }
        });
        background.add(bttGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 120, 30));

        bttModificar1.setBackground(new java.awt.Color(102, 0, 102));
        bttModificar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar1.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar1.setText("Modificar Factura");
        bttModificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar1ActionPerformed(evt);
            }
        });
        background.add(bttModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 120, 30));

        bttCancelar.setBackground(new java.awt.Color(102, 0, 102));
        bttCancelar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttCancelar.setForeground(new java.awt.Color(204, 204, 204));
        bttCancelar.setText("Eliminar Factura");
        bttCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarActionPerformed(evt);
            }
        });
        background.add(bttCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 130, 30));

        TablaArticulo.setBackground(new java.awt.Color(255, 255, 255));
        TablaArticulo.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        TablaArticulo.setForeground(new java.awt.Color(51, 0, 51));
        TablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cantidad", "Nombre", "Precio Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaArticulo.setGridColor(new java.awt.Color(0, 0, 0));
        TablaArticulo.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TablaArticulo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaArticulo);
        if (TablaArticulo.getColumnModel().getColumnCount() > 0) {
            TablaArticulo.getColumnModel().getColumn(0).setMinWidth(100);
            TablaArticulo.getColumnModel().getColumn(0).setPreferredWidth(100);
            TablaArticulo.getColumnModel().getColumn(0).setMaxWidth(100);
            TablaArticulo.getColumnModel().getColumn(1).setMinWidth(100);
            TablaArticulo.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaArticulo.getColumnModel().getColumn(1).setMaxWidth(100);
            TablaArticulo.getColumnModel().getColumn(2).setResizable(false);
            TablaArticulo.getColumnModel().getColumn(3).setMinWidth(100);
            TablaArticulo.getColumnModel().getColumn(3).setPreferredWidth(100);
            TablaArticulo.getColumnModel().getColumn(3).setMaxWidth(100);
            TablaArticulo.getColumnModel().getColumn(4).setMinWidth(100);
            TablaArticulo.getColumnModel().getColumn(4).setPreferredWidth(100);
            TablaArticulo.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 750, 190));

        bttLimpiar.setBackground(new java.awt.Color(102, 0, 102));
        bttLimpiar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("Limpiar");
        bttLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        background.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 110, 30));

        lbFECHA.setBackground(new java.awt.Color(255, 255, 255));
        lbFECHA.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbFECHA.setForeground(new java.awt.Color(51, 0, 51));
        lbFECHA.setText("Fecha: ");
        background.add(lbFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        lbFecha.setBackground(new java.awt.Color(255, 255, 255));
        lbFecha.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 130, 20));

        lbCorrelativo.setBackground(new java.awt.Color(255, 255, 255));
        lbCorrelativo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCorrelativo.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbCorrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, 20));

        lbNombreArticulo.setBackground(new java.awt.Color(255, 255, 255));
        lbNombreArticulo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombreArticulo.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 150, 20));

        lbPrecioUnitario.setBackground(new java.awt.Color(255, 255, 255));
        lbPrecioUnitario.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbPrecioUnitario.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 120, 20));

        bttAgregar_Articulo.setBackground(new java.awt.Color(153, 0, 153));
        bttAgregar_Articulo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttAgregar_Articulo.setForeground(new java.awt.Color(204, 204, 204));
        bttAgregar_Articulo.setText("Agregar artículo");
        bttAgregar_Articulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregar_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregar_ArticuloActionPerformed(evt);
            }
        });
        background.add(bttAgregar_Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 30));

        bttModificar_Articulo.setBackground(new java.awt.Color(153, 0, 153));
        bttModificar_Articulo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar_Articulo.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar_Articulo.setText("Modificar artículo");
        bttModificar_Articulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar_ArticuloActionPerformed(evt);
            }
        });
        background.add(bttModificar_Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 140, 30));

        bttEliminar_Articulo.setBackground(new java.awt.Color(153, 0, 153));
        bttEliminar_Articulo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttEliminar_Articulo.setForeground(new java.awt.Color(204, 204, 204));
        bttEliminar_Articulo.setText("Eliminar artículo");
        bttEliminar_Articulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminar_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminar_ArticuloActionPerformed(evt);
            }
        });
        background.add(bttEliminar_Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 140, 30));

        bttBuscar_Artiulo.setBackground(new java.awt.Color(153, 0, 153));
        bttBuscar_Artiulo.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar_Artiulo.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar_Artiulo.setText("Buscar artículo");
        bttBuscar_Artiulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar_Artiulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscar_ArtiuloActionPerformed(evt);
            }
        });
        background.add(bttBuscar_Artiulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 120, 30));

        lbCCliente.setBackground(new java.awt.Color(255, 255, 255));
        lbCCliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCCliente.setForeground(new java.awt.Color(51, 0, 51));
        lbCCliente.setText("Cod. Cliente:");
        background.add(lbCCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, 20));

        txNITcliente.setBackground(new java.awt.Color(255, 255, 255));
        txNITcliente.setForeground(new java.awt.Color(0, 0, 0));
        txNITcliente.setBorder(null);
        txNITcliente.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNITcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));
        background.add(sCodigoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, 15));

        lbNOMBREcliente.setBackground(new java.awt.Color(255, 255, 255));
        lbNOMBREcliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNOMBREcliente.setForeground(new java.awt.Color(51, 0, 51));
        lbNOMBREcliente.setText("Nombre:");
        background.add(lbNOMBREcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        lbNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        lbNombreCliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombreCliente.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 200, 20));

        lbNiT.setBackground(new java.awt.Color(255, 255, 255));
        lbNiT.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNiT.setForeground(new java.awt.Color(51, 0, 51));
        lbNiT.setText("NIT cliente:");
        background.add(lbNiT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lbCodigoCliente.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigoCliente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigoCliente.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 50, 20));

        btt_Buscar_Cliente.setBackground(new java.awt.Color(153, 0, 153));
        btt_Buscar_Cliente.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btt_Buscar_Cliente.setForeground(new java.awt.Color(204, 204, 204));
        btt_Buscar_Cliente.setText("Buscar cliente");
        btt_Buscar_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btt_Buscar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_Buscar_ClienteActionPerformed(evt);
            }
        });
        background.add(btt_Buscar_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 120, 30));

        lbIDcajero.setBackground(new java.awt.Color(255, 255, 255));
        lbIDcajero.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbIDcajero.setForeground(new java.awt.Color(51, 0, 51));
        lbIDcajero.setText("ID Cajero:");
        background.add(lbIDcajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        txIDcajero.setBackground(new java.awt.Color(255, 255, 255));
        txIDcajero.setForeground(new java.awt.Color(0, 0, 0));
        txIDcajero.setBorder(null);
        txIDcajero.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txIDcajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 50, -1));
        background.add(sCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, 15));

        lbNUMEROcaja.setBackground(new java.awt.Color(255, 255, 255));
        lbNUMEROcaja.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNUMEROcaja.setForeground(new java.awt.Color(51, 0, 51));
        lbNUMEROcaja.setText("No. Caja:");
        background.add(lbNUMEROcaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        txNumero_Caja.setBackground(new java.awt.Color(255, 255, 255));
        txNumero_Caja.setForeground(new java.awt.Color(0, 0, 0));
        txNumero_Caja.setBorder(null);
        txNumero_Caja.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNumero_Caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 50, -1));
        background.add(sCodigoE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 50, 15));

        lbNOMBREempleado.setBackground(new java.awt.Color(255, 255, 255));
        lbNOMBREempleado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNOMBREempleado.setForeground(new java.awt.Color(51, 0, 51));
        lbNOMBREempleado.setText("Nombre:");
        background.add(lbNOMBREempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        lbNombreEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        lbNombreEmpleado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombreEmpleado.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 200, 20));

        lbCEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        lbCEmpleado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCEmpleado.setForeground(new java.awt.Color(51, 0, 51));
        lbCEmpleado.setText("Cod. Empleado:");
        background.add(lbCEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, 20));

        lbCodEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        lbCodEmpleado.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodEmpleado.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbCodEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 70, 20));

        btt_BuscarEmpleado.setBackground(new java.awt.Color(153, 0, 153));
        btt_BuscarEmpleado.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btt_BuscarEmpleado.setForeground(new java.awt.Color(204, 204, 204));
        btt_BuscarEmpleado.setText("Buscar Empleado");
        btt_BuscarEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btt_BuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_BuscarEmpleadoActionPerformed(evt);
            }
        });
        background.add(btt_BuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 120, 30));

        bttVisualizar.setBackground(new java.awt.Color(102, 0, 102));
        bttVisualizar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttVisualizar.setForeground(new java.awt.Color(204, 204, 204));
        bttVisualizar.setText("Visualizar");
        bttVisualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVisualizarActionPerformed(evt);
            }
        });
        background.add(bttVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 120, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_BuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_BuscarEmpleadoActionPerformed
        if (txIDcajero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese ID de cajero");
        }
        else 
        {
            E = ab_Empleado.A_invCajero();
            
            if (ab_Empleado.VCajeroFac(parseInt(txIDcajero.getText())) != -1){
                int i = ab_Empleado.VCajeroFac(parseInt(txIDcajero.getText()));
                lbNombreEmpleado.setText(E.get(i).getNombre());
                lbCodEmpleado.setText(Integer.toString(E.get(i).getCodigo()));
            }
            else {
                JOptionPane.showMessageDialog(null, "Empleado no existente");
                txIDcajero.setText("");
                txIDcajero.requestFocus();
            }
        }
    }//GEN-LAST:event_btt_BuscarEmpleadoActionPerformed

    private void btt_Buscar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_Buscar_ClienteActionPerformed
        if (txNITcliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese NIT de cliente");
        }
        else 
        {
            try {
                ab_Cliente3597.SalvarA_Cliente();
            } catch (IOException | ClassNotFoundException ex) {
               ex.printStackTrace();
            }
            
            C = ab_Cliente3597.A_inv();
            
            if (ab_Cliente3597.VClienteFac(txNITcliente.getText()) != -1){
                int i = ab_Cliente3597.VClienteFac(txNITcliente.getText());
                lbNombreCliente.setText(C.get(i).getNombre());
                lbCodigoCliente.setText(Integer.toString(C.get(i).getCodigo()));
            }
            else {
                int op = JOptionPane.showConfirmDialog(null, "\nCliente no existente segun NIT \n¿Desea agregar un nuevo cliente?\n", "CLIENTE NO ENCONTRADO", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                if (op == 0){
                    F_Cliente_3597 c = new F_Cliente_3597();
                }
                else{
                    txNITcliente.setText("");
                    lbNombreCliente.setText(null);
                    lbCodigoCliente.setText(null);
                    txNITcliente.requestFocus();
                }
            }
        } 
    }//GEN-LAST:event_btt_Buscar_ClienteActionPerformed

    private void bttBuscar_ArtiuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscar_ArtiuloActionPerformed
        if (txCodArticulo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, ingrese código de artículo");
        }
        else{
            A = ab_Articulo3597.A_inv();
            if (ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText())) != -1){
                int i = ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText()));
                lbNombreArticulo.setText(A.get(i).getNombre());
                lbPrecioUnitario.setText(Double.toString(A.get(i).getPrecioUnitario()));
            }
            else{
                JOptionPane.showMessageDialog(null, "Artículo no existente según código de artículo");
                limpiarArticulo();
            }
        }
    }//GEN-LAST:event_bttBuscar_ArtiuloActionPerformed

    private void bttAgregar_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregar_ArticuloActionPerformed
        if (txNumero_Caja.getText().isEmpty() || txIDcajero.getText().isEmpty() || lbNombreEmpleado.getText() == null ||
            lbCodEmpleado.getText() == null || txNITcliente.getText().isEmpty() || lbNombreCliente.getText() == null ||
            lbCodigoCliente.getText() == null || txCodArticulo.getText().isEmpty() || lbNombreArticulo.getText() == null ||
            lbPrecioUnitario.getText() == null || txCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesitan todos los campos llenos para completar esta acción.\nInténtelo de nuevo");
        }
        else{
            if (ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText())) != -1){
                int i = ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText()));
                A = ab_Articulo3597.A_inv();
                Double total = parseInt(txCantidad.getText()) * parseDouble(lbPrecioUnitario.getText());

                Articulo_3597 a = new Articulo_3597(parseInt(txCodArticulo.getText()), 
                                                    A.get(i).getNombre(), 
                                                    Double.toString(total), 
                                                    parseInt(txCantidad.getText()), 
                                                    A.get(i).getPrecioUnitario(), 
                                                    A.get(i).getCantidad());

                if (ab_Factura3597.VerificarArticulo(a) == - 1){
                    if (A.get(i).getCantidad() >= a.getCantidad()){
                        ab_Factura3597.G_Array(a);
                        DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
                        Object[] fila = new Object[5];
                        fila[0] = a.getCodigo();
                        fila[1] = a.getCantidad();
                        fila[2] = a.getNombre();
                        fila[3] = a.getPrecioUnitario();
                        fila[4] = a.getDescripción();
                        modelo.addRow(fila);

                        a.setcProveedor(a.getcProveedor() - a.getCantidad());
                        limpiarArticulo();                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Cantidad de Articulo: '" + A.get(i).getNombre() + 
                                                    "' insuficiente para realizar esta acción.\nStock: " + A.get(i).getCantidad());
                        txCantidad.setText("");
                        txCantidad.requestFocus();                    
                    }
                }
                else{
                    art = ab_Factura3597.A_DetalleArticulos();
                    int p = ab_Factura3597.VerificarArticulo(a);

                    if (art.get(p).getcProveedor() >= a.getCantidad()){
                        art.get(p).setCantidad(art.get(p).getCantidad() + a.getCantidad());
                        art.get(p).setDescripción(Double.toString(parseDouble(a.getDescripción())+ parseDouble(art.get(p).getDescripción())));
                        art.get(p).setcProveedor(art.get(p).getcProveedor() - a.getCantidad());

                        TablaArticulo.setValueAt(art.get(p).getCantidad(), p, 1);
                        TablaArticulo.setValueAt(art.get(p).getDescripción(), p, 4);
                        limpiarArticulo(); 
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Cantidad de Articulo: '" + A.get(i).getNombre() + 
                                                    "'\n insuficiente para realizar esta acción.\nStock: " + art.get(p).getcProveedor());
                        txCantidad.setText("");
                        txCantidad.requestFocus();                           
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Artículo no existente\nCódigo de artículo no coincide con los demás campos.");
                limpiarArticulo();
                }
        }
    }//GEN-LAST:event_bttAgregar_ArticuloActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Los datos ingresados se perderán\n¿Desea continuar de todos modos?", "Limpiar pantalla", JOptionPane.WARNING_MESSAGE);
        
        if (op == 0){
            limpiar();          
        }

    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void bttModificar_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar_ArticuloActionPerformed
        if (txNumero_Caja.getText().isEmpty() || txIDcajero.getText().isEmpty() || lbNombreEmpleado.getText() == null ||
            lbCodEmpleado.getText() == null || txNITcliente.getText().isEmpty() || lbNombreCliente.getText() == null ||
            lbCodigoCliente.getText() == null || txCodArticulo.getText().isEmpty() || lbNombreArticulo.getText() == null ||
            lbPrecioUnitario.getText() == null || txCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesitan todos los campos llenos para completar esta acción.\nInténtelo de nuevo");
        }
        else{
            if (ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText())) != -1){
                int i = ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText()));
                A = ab_Articulo3597.A_inv();
                Double total = parseInt(txCantidad.getText()) * parseDouble(lbPrecioUnitario.getText());

                Articulo_3597 a = new Articulo_3597(parseInt(txCodArticulo.getText()), 
                                                    A.get(i).getNombre(), 
                                                    Double.toString(total), 
                                                    parseInt(txCantidad.getText()), 
                                                    A.get(i).getPrecioUnitario(), 
                                                    A.get(i).getCantidad());  
                
                
                if (ab_Factura3597.VerificarArticulo(a) != -1){
                    int p = ab_Factura3597.VerificarArticulo(a);
                    if (A.get(i).getCantidad() >= a.getCantidad()){
                        art = ab_Factura3597.A_DetalleArticulos();
                        
                        art.get(p).setCantidad(a.getCantidad());
                        art.get(p).setDescripción(a.getDescripción());
                        art.get(p).setcProveedor(A.get(i).getCantidad() - a.getCantidad());
                        
                        TablaArticulo.setValueAt(a.getCantidad(), p, 1);
                        TablaArticulo.setValueAt(a.getDescripción(), p, 4);
                        
                        limpiarArticulo();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Cantidad de Articulo: '" + A.get(i).getNombre() + 
                                                    "' insuficiente para realizar esta acción.\nStock: " + A.get(i).getCantidad());
                        txCantidad.setText("");
                        txCantidad.requestFocus();                        
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Artículo '" + A.get(i).getNombre() + "' no existente\nen detalle de factura.");
                    limpiarArticulo();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Artículo no existente\nCódigo de artículo no coincide con los demás campos.");
                limpiarArticulo();
            }
        }
    }//GEN-LAST:event_bttModificar_ArticuloActionPerformed

    private void bttEliminar_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminar_ArticuloActionPerformed
        if (txNumero_Caja.getText().isEmpty() || txIDcajero.getText().isEmpty() || lbNombreEmpleado.getText() == null ||
            lbCodEmpleado.getText() == null || txNITcliente.getText().isEmpty() || lbNombreCliente.getText() == null ||
            lbCodigoCliente.getText() == null || txCodArticulo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesitan todos los campos llenos para completar esta acción.\nInténtelo de nuevo");
        }
        else{
            if (ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText())) != -1){
                A = ab_Articulo3597.A_inv();
                int i = ab_Articulo3597.VArticuloFac(parseInt(txCodArticulo.getText()));

                Articulo_3597 a = new Articulo_3597();
                a.setCodigo(parseInt(txCodArticulo.getText()));
                
                if (ab_Factura3597.VerificarArticulo(a) != -1){
                    int p = ab_Factura3597.VerificarArticulo(a);
                    art = ab_Factura3597.A_DetalleArticulos();
                    
                    DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
                    modelo.removeRow(p);
                    art.remove(p);
                    limpiarArticulo();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Artículo '" + A.get(i).getNombre() + "' no existente\nen detalle de factura.");
                    limpiarArticulo();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Artículo no existente\nCódigo de artículo no coincide con los demás campos.");
                limpiarArticulo(); 
            }
        }
    }//GEN-LAST:event_bttEliminar_ArticuloActionPerformed

    private void bttGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGenerarActionPerformed
        if (txNumero_Caja.getText().isEmpty() || txIDcajero.getText().isEmpty() || lbNombreEmpleado.getText() == null ||
            lbCodEmpleado.getText() == null || txNITcliente.getText().isEmpty() || lbNombreCliente.getText() == null ||
            lbCodigoCliente.getText() == null ){
            JOptionPane.showMessageDialog(null, "Se necesitan los campos de 'cajero' y 'cliente' para continuar.");
        }
        else{
            if (ab_Empleado.VCajeroFac(parseInt(txIDcajero.getText())) != -1 && ab_Cliente3597.VClienteFac(txNITcliente.getText()) != -1){
                
                DetalleFactura_3597 F = new DetalleFactura_3597();
                F.setCodigo(parseInt(lbCorrelativo.getText()));
                F.setIDempleado(parseInt(txIDcajero.getText()));
                F.setNITcliente(parseInt(txNITcliente.getText()));
                F.setFecha(lbFecha.getText());
                F.setCaja(parseInt(txNumero_Caja.getText()));
                
                if (ab_Factura3597.Verificar_Factura(F) == -1){
                    ab_Factura3597.AgregarFactura(F);
                    limpiar();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Factura ya existente según correlativo");
                }
            }   
        }
    }//GEN-LAST:event_bttGenerarActionPerformed

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        F_Reporte3597 R = new F_Reporte3597(ab_Factura3597.A_invFactura());
    }//GEN-LAST:event_bttReporteActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed
        String op = JOptionPane.showInputDialog("Ingrese correlativo de factura que desea MODIFICAR");
        
        DetalleFactura_3597 F = new DetalleFactura_3597(); 
        F.setCodigo(parseInt(op));
       
        
        if (ab_Factura3597.BuscarFactura(F)){
            
            DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
            modelo.getDataVector().removeAllElements();
            TablaArticulo.updateUI();
            
            E = ab_Empleado.A_invCajero();
            D = ab_Factura3597.A_invFactura();
            C = ab_Cliente3597.A_inv();
            
            int pf = ab_Factura3597.Verificar_Factura(F);
            int pe = ab_Empleado.VCajeroFac(D.get(pf).getIDempleado());
            int pc = ab_Cliente3597.VClienteFac(Integer.toString(D.get(pf).getNITcliente()));
            
            lbCorrelativo.setText(op);
            lbFecha.setText(D.get(pf).getFecha());
            txNumero_Caja.setText(Integer.toString(D.get(pf).getCaja()));
            txIDcajero.setText(Integer.toString(D.get(pf).getIDempleado()));
            lbNombreEmpleado.setText(E.get(pe).getNombre());
            lbCodEmpleado.setText(Integer.toString(E.get(pe).getCodigo()));
            txNITcliente.setText(Integer.toString(D.get(pf).getNITcliente()));
            lbNombreCliente.setText(C.get(pc).getNombre());
            lbCodigoCliente.setText(Integer.toString(C.get(pc).getCodigo()));
            
//            DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
            Object[] fila = new Object[5];
            
            for (Articulo_3597 f : D.get(pf).getArrayArticulos()) {
                fila[0] = f.getCodigo();
                fila[1] = f.getCantidad();
                fila[2] = f.getNombre();
                fila[3] = f.getPrecioUnitario();
                fila[4] = f.getDescripción();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_bttBuscarActionPerformed

    private void bttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarActionPerformed
        String op = JOptionPane.showInputDialog("Ingrese correlativo de factura a CANCELAR");
        DetalleFactura_3597 F = new DetalleFactura_3597(); 
        F.setCodigo(parseInt(op));
        
        ab_Factura3597.CancelarFactura(F);
        limpiar();
    }//GEN-LAST:event_bttCancelarActionPerformed

    private void bttModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar1ActionPerformed
        if (txNumero_Caja.getText().isEmpty() || txIDcajero.getText().isEmpty() || lbNombreEmpleado.getText() == null ||
            lbCodEmpleado.getText() == null || txNITcliente.getText().isEmpty() || lbNombreCliente.getText() == null ||
            lbCodigoCliente.getText() == null ){
            JOptionPane.showMessageDialog(null, "Se necesitan los campos de 'cajero' y 'cliente' para continuar.");
        }
        else{
            if (ab_Empleado.VCajeroFac(parseInt(txIDcajero.getText())) != -1 && ab_Cliente3597.VClienteFac(txNITcliente.getText()) != -1){
                
                DetalleFactura_3597 F = new DetalleFactura_3597();
                F.setCodigo(parseInt(lbCorrelativo.getText()));
                
                int op = JOptionPane.showConfirmDialog(null, "¿Está seguro de modificar la factura con correlativo " + F.getCodigo() + "?");
                
                if (op == 0){
                    ab_Factura3597.ModificarFactura(F);
                }
                
                limpiar();
            }   
        }
    }//GEN-LAST:event_bttModificar1ActionPerformed

    private void bttVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizarActionPerformed
        String op = JOptionPane.showInputDialog("Ingrese correlativo de factura a visualizar");
        
        DetalleFactura_3597 F = new DetalleFactura_3597();
        F.setCodigo(parseInt(op));
        
        ab_Factura3597.VisualizarFactura(F);
    }//GEN-LAST:event_bttVisualizarActionPerformed

    public void limpiar(){
        txNumero_Caja.setText("");
        txIDcajero.setText("");
        lbNombreEmpleado.setText(null);
        lbCodEmpleado.setText(null);
        txNITcliente.setText("");
        lbNombreCliente.setText(null);
        lbCodigoCliente.setText(null);
        txCodArticulo.setText("");
        lbNombreArticulo.setText(null);
        lbPrecioUnitario.setText(null);
        txCantidad.setText("");
        txNumero_Caja.requestFocus();

        DefaultTableModel modelo = (DefaultTableModel) TablaArticulo.getModel();
        modelo.getDataVector().removeAllElements();
        TablaArticulo.updateUI();

        lbCorrelativo.setText(Integer.toString(ab_Factura3597.corelativoF()));
        ab_Factura3597.clean();  
    }
    
    public void limpiarArticulo(){
        txCodArticulo.setText("");
        lbNombreArticulo.setText(null);
        lbPrecioUnitario.setText(null);
        txCantidad.setText("");
        txCodArticulo.requestFocus();   
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaArticulo;
    private javax.swing.JPanel background;
    private javax.swing.JButton bttAgregar_Articulo;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttBuscar_Artiulo;
    private javax.swing.JButton bttCancelar;
    private javax.swing.JButton bttEliminar_Articulo;
    private javax.swing.JButton bttGenerar;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar1;
    private javax.swing.JButton bttModificar_Articulo;
    private javax.swing.JButton bttReporte;
    private javax.swing.JButton bttVisualizar;
    private javax.swing.JButton btt_BuscarEmpleado;
    private javax.swing.JButton btt_Buscar_Cliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCArticulo;
    private javax.swing.JLabel lbCCliente;
    private javax.swing.JLabel lbCEmpleado;
    private javax.swing.JLabel lbCORRELATIVO;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCodEmpleado;
    private javax.swing.JLabel lbCodigoCliente;
    private javax.swing.JLabel lbCorrelativo;
    private javax.swing.JLabel lbFECHA;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbIDcajero;
    private javax.swing.JLabel lbNOMBREcliente;
    private javax.swing.JLabel lbNOMBREempleado;
    private javax.swing.JLabel lbNUMEROcaja;
    private javax.swing.JLabel lbNiT;
    private javax.swing.JLabel lbNombreARTICULO;
    private javax.swing.JLabel lbNombreArticulo;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombreEmpleado;
    private javax.swing.JLabel lbPRECIOunitario;
    private javax.swing.JLabel lbPrecioUnitario;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JSeparator sCantidad;
    private javax.swing.JSeparator sCodigoA;
    private javax.swing.JSeparator sCodigoC;
    private javax.swing.JSeparator sCodigoE1;
    private javax.swing.JSeparator sID;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txCodArticulo;
    private javax.swing.JTextField txIDcajero;
    private javax.swing.JTextField txNITcliente;
    private javax.swing.JTextField txNumero_Caja;
    // End of variables declaration//GEN-END:variables
}
