
package Vista;

import javax.swing.JFrame;

public class F_Menu_3597 extends javax.swing.JFrame {

       
    public F_Menu_3597() {

        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        bttArtículos = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();
        bttProveedores2 = new javax.swing.JButton();
        bttClientes1 = new javax.swing.JButton();
        bttEmpleados1 = new javax.swing.JButton();
        bttFacturacion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, -1));

        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("MENÚ");
        Background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        bttArtículos.setBackground(new java.awt.Color(102, 0, 102));
        bttArtículos.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttArtículos.setForeground(new java.awt.Color(204, 204, 204));
        bttArtículos.setText("Artículos");
        bttArtículos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttArtículosActionPerformed(evt);
            }
        });
        Background.add(bttArtículos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 140, 50));

        bttReportes.setBackground(new java.awt.Color(102, 0, 102));
        bttReportes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttReportes.setForeground(new java.awt.Color(204, 204, 204));
        bttReportes.setText("Reportes HTML");
        bttReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReportesActionPerformed(evt);
            }
        });
        Background.add(bttReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 140, 50));

        bttProveedores2.setBackground(new java.awt.Color(102, 0, 102));
        bttProveedores2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttProveedores2.setForeground(new java.awt.Color(204, 204, 204));
        bttProveedores2.setText("Proveedores");
        bttProveedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProveedores2ActionPerformed(evt);
            }
        });
        Background.add(bttProveedores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 50));

        bttClientes1.setBackground(new java.awt.Color(102, 0, 102));
        bttClientes1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttClientes1.setForeground(new java.awt.Color(204, 204, 204));
        bttClientes1.setText("Clientes");
        bttClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttClientes1ActionPerformed(evt);
            }
        });
        Background.add(bttClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 140, 50));

        bttEmpleados1.setBackground(new java.awt.Color(102, 0, 102));
        bttEmpleados1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttEmpleados1.setForeground(new java.awt.Color(204, 204, 204));
        bttEmpleados1.setText("Empleados");
        bttEmpleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEmpleados1ActionPerformed(evt);
            }
        });
        Background.add(bttEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 140, 50));

        bttFacturacion1.setBackground(new java.awt.Color(102, 0, 102));
        bttFacturacion1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        bttFacturacion1.setForeground(new java.awt.Color(204, 204, 204));
        bttFacturacion1.setText("Facturación");
        bttFacturacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttFacturacion1ActionPerformed(evt);
            }
        });
        Background.add(bttFacturacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttProveedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProveedores2ActionPerformed
        F_Proveedor_3597 Proveedor = new F_Proveedor_3597();
    }//GEN-LAST:event_bttProveedores2ActionPerformed

    private void bttArtículosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttArtículosActionPerformed
        F_Articulo_3597 Articulo = new F_Articulo_3597();
    }//GEN-LAST:event_bttArtículosActionPerformed

    private void bttClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClientes1ActionPerformed
        F_Cliente3597 Cliente = new F_Cliente3597();
    }//GEN-LAST:event_bttClientes1ActionPerformed

    private void bttEmpleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEmpleados1ActionPerformed
        F_Empleado_3597 Empleado = new F_Empleado_3597();
    }//GEN-LAST:event_bttEmpleados1ActionPerformed

    private void bttFacturacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttFacturacion1ActionPerformed
        F_Factura Factura = new F_Factura();
    }//GEN-LAST:event_bttFacturacion1ActionPerformed

    private void bttReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReportesActionPerformed
        F_Reportes3597 Reporte = new F_Reportes3597();
    }//GEN-LAST:event_bttReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Menu_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Menu_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Menu_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Menu_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Menu_3597().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton bttArtículos;
    private javax.swing.JButton bttClientes1;
    private javax.swing.JButton bttEmpleados1;
    private javax.swing.JButton bttFacturacion1;
    private javax.swing.JButton bttProveedores2;
    private javax.swing.JButton bttReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
