/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.AB_Cliente3597;
import Controlador.AB_Empleado;
import Modelo.Articulo_3597;
import Modelo.Cliente_3597;
import Modelo.DetalleFactura_3597;
import Modelo.Empleado;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class V_Factura3597 extends javax.swing.JFrame {

    ArrayList <Empleado> cajeros = new ArrayList();
    ArrayList <Cliente_3597> clientes = new ArrayList();
    ArrayList <Articulo_3597> detallefactura = new ArrayList();
    
    AB_Empleado ab_Empleado3597 = new AB_Empleado();
    AB_Cliente3597 ab_Cliente3597 = new AB_Cliente3597();
    
    public V_Factura3597(DetalleFactura_3597 factura) {
        initComponents();
        
        try {
            ab_Empleado3597.SalvarA_Empleado();
            ab_Cliente3597.SalvarA_Cliente();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(V_Factura3597.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        lbCaja.setText(Integer.toString(factura.getCaja()));
        lbCorrelativo.setText(Integer.toString(factura.getCodigo()));
        lbFecha.setText(factura.getFecha());
                
        int e = ab_Empleado3597.VCajeroFac(factura.getIDempleado());
        cajeros = ab_Empleado3597.A_invCajero();
        lbCajero.setText(cajeros.get(e).getNombre());
        
        int c = ab_Cliente3597.VClienteFac(Integer.toString(factura.getNITcliente()));
        clientes = ab_Cliente3597.A_inv();
        lbNIT.setText(Integer.toString(factura.getNITcliente()));
        lbCliente.setText(clientes.get(c).getNombre());
        lbDireccion.setText(clientes.get(e).getDireccion());
        
        //detallefactura = new ArrayList(factura.getArrayArticulos());
        detallefactura = factura.getArrayArticulos();
        
        for (Iterator <Articulo_3597> it = detallefactura.iterator(); it.hasNext();){
            Articulo_3597 a = it.next();
            DefaultTableModel modelo = (DefaultTableModel) tbFactura.getModel();
            Object[] fila = new Object[3];
            fila[0] = a.getCantidad();
            fila[1] = a.getNombre();
            fila[2] = a.getDescripción();
            modelo.addRow(fila);
        }
        
        lbSubtotal.setText(Double.toString(factura.getSubtotal()));
        lbIVA.setText(String.format("%.2f", factura.getIVA()));
        lbTotal.setText(String.format("%.2f", factura.getTotal()));
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCorrelativo = new javax.swing.JLabel();
        lbMas1 = new javax.swing.JLabel();
        lbMas2 = new javax.swing.JLabel();
        lbMas3 = new javax.swing.JLabel();
        lbCaja = new javax.swing.JLabel();
        lbMas5 = new javax.swing.JLabel();
        lbMas6 = new javax.swing.JLabel();
        lbMas7 = new javax.swing.JLabel();
        lbCajero = new javax.swing.JLabel();
        lbMas8 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbMas9 = new javax.swing.JLabel();
        lbMas10 = new javax.swing.JLabel();
        lbMas11 = new javax.swing.JLabel();
        lbNIT = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFactura = new javax.swing.JTable();
        lbMas12 = new javax.swing.JLabel();
        lbMas13 = new javax.swing.JLabel();
        lbMas14 = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JLabel();
        lbIVA = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 641));
        setMinimumSize(new java.awt.Dimension(400, 640));
        setSize(new java.awt.Dimension(400, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 640));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCorrelativo.setBackground(new java.awt.Color(255, 255, 255));
        lbCorrelativo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCorrelativo.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbCorrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 20));

        lbMas1.setBackground(new java.awt.Color(255, 255, 255));
        lbMas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbMas1.setForeground(new java.awt.Color(51, 0, 51));
        lbMas1.setText("SUPERMERCADO MAS");
        jPanel1.add(lbMas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        lbMas2.setBackground(new java.awt.Color(255, 255, 255));
        lbMas2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas2.setForeground(new java.awt.Color(51, 0, 51));
        lbMas2.setText("DOCUMENTO TRIBUTARIO ELECTRÓNICO");
        jPanel1.add(lbMas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lbMas3.setBackground(new java.awt.Color(255, 255, 255));
        lbMas3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas3.setForeground(new java.awt.Color(51, 0, 51));
        lbMas3.setText("Factura Electrónica");
        jPanel1.add(lbMas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lbCaja.setBackground(new java.awt.Color(255, 255, 255));
        lbCaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCaja.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, 20));

        lbMas5.setBackground(new java.awt.Color(255, 255, 255));
        lbMas5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas5.setForeground(new java.awt.Color(51, 0, 51));
        lbMas5.setText("NÚMERO: ");
        jPanel1.add(lbMas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lbMas6.setBackground(new java.awt.Color(255, 255, 255));
        lbMas6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas6.setForeground(new java.awt.Color(51, 0, 51));
        lbMas6.setText("ATENDIÓ:");
        jPanel1.add(lbMas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lbMas7.setBackground(new java.awt.Color(255, 255, 255));
        lbMas7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas7.setForeground(new java.awt.Color(51, 0, 51));
        lbMas7.setText("No. Caja:");
        jPanel1.add(lbMas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lbCajero.setBackground(new java.awt.Color(255, 255, 255));
        lbCajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCajero.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 240, 20));

        lbMas8.setBackground(new java.awt.Color(255, 255, 255));
        lbMas8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas8.setForeground(new java.awt.Color(51, 0, 51));
        lbMas8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMas8.setText("Total:     Q.");
        jPanel1.add(lbMas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        lbFecha.setBackground(new java.awt.Color(255, 255, 255));
        lbFecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 20));

        lbMas9.setBackground(new java.awt.Color(255, 255, 255));
        lbMas9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas9.setForeground(new java.awt.Color(51, 0, 51));
        lbMas9.setText("Fecha: ");
        jPanel1.add(lbMas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lbMas10.setBackground(new java.awt.Color(255, 255, 255));
        lbMas10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas10.setForeground(new java.awt.Color(51, 0, 51));
        lbMas10.setText("N.I.T:");
        jPanel1.add(lbMas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lbMas11.setBackground(new java.awt.Color(255, 255, 255));
        lbMas11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas11.setForeground(new java.awt.Color(51, 0, 51));
        lbMas11.setText("Nombre:");
        jPanel1.add(lbMas11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lbNIT.setBackground(new java.awt.Color(255, 255, 255));
        lbNIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNIT.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 230, 20));

        lbCliente.setBackground(new java.awt.Color(255, 255, 255));
        lbCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCliente.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, 20));

        lbDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lbDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 230, 20));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbFactura.setBackground(new java.awt.Color(255, 255, 255));
        tbFactura.setForeground(new java.awt.Color(51, 0, 51));
        tbFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CANT", "DESCRIPCIÓN", "TOTAL"
            }
        ));
        tbFactura.setSelectionBackground(new java.awt.Color(51, 0, 51));
        tbFactura.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbFactura);
        if (tbFactura.getColumnModel().getColumnCount() > 0) {
            tbFactura.getColumnModel().getColumn(0).setMinWidth(50);
            tbFactura.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbFactura.getColumnModel().getColumn(0).setMaxWidth(50);
            tbFactura.getColumnModel().getColumn(2).setMinWidth(100);
            tbFactura.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbFactura.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 340, 200));

        lbMas12.setBackground(new java.awt.Color(255, 255, 255));
        lbMas12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas12.setForeground(new java.awt.Color(51, 0, 51));
        lbMas12.setText("Dirección:");
        jPanel1.add(lbMas12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lbMas13.setBackground(new java.awt.Color(255, 255, 255));
        lbMas13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas13.setForeground(new java.awt.Color(51, 0, 51));
        lbMas13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMas13.setText("Subtotal:    Q. ");
        jPanel1.add(lbMas13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        lbMas14.setBackground(new java.awt.Color(255, 255, 255));
        lbMas14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMas14.setForeground(new java.awt.Color(51, 0, 51));
        lbMas14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMas14.setText("IVA:     Q.");
        jPanel1.add(lbMas14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, 20));

        lbSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        lbSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSubtotal.setForeground(new java.awt.Color(51, 0, 51));
        lbSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 90, 20));

        lbIVA.setBackground(new java.awt.Color(255, 255, 255));
        lbIVA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIVA.setForeground(new java.awt.Color(51, 0, 51));
        lbIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 90, 20));

        lbTotal.setBackground(new java.awt.Color(255, 255, 255));
        lbTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(51, 0, 51));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 640));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCaja;
    private javax.swing.JLabel lbCajero;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbCorrelativo;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbIVA;
    private javax.swing.JLabel lbMas1;
    private javax.swing.JLabel lbMas10;
    private javax.swing.JLabel lbMas11;
    private javax.swing.JLabel lbMas12;
    private javax.swing.JLabel lbMas13;
    private javax.swing.JLabel lbMas14;
    private javax.swing.JLabel lbMas2;
    private javax.swing.JLabel lbMas3;
    private javax.swing.JLabel lbMas5;
    private javax.swing.JLabel lbMas6;
    private javax.swing.JLabel lbMas7;
    private javax.swing.JLabel lbMas8;
    private javax.swing.JLabel lbMas9;
    private javax.swing.JLabel lbNIT;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTable tbFactura;
    // End of variables declaration//GEN-END:variables
}
